// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoAPI.Data;

namespace ProjetoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211029175237_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ProjetoAPI.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("descricao");

                    b.Property<string>("Divisao")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("divisao");

                    b.Property<int>("Estoque")
                        .HasColumnType("integer")
                        .HasColumnName("estoque");

                    b.Property<string>("Fornecedor")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("fornecedor");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("imagem");

                    b.Property<string>("Nome")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.Property<DateTime>("Reg_alt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reg_alt");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("tamanho");

                    b.Property<string>("Usuario_alt")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("usuario_alt");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
